import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root"
})
export class currencyDetail {

    public currencyDetails = {
        "UAE": "د.إ",
        "Afghanistan": "Af",
        "Albania": "L",
        "Armenia": "Դ",
        "Angola": "Kz",
        "Argentina": "$",
        "Australia": "$",
        "Kiribati": "$",
        "Coconut Islands": "$",
        "Nauru": "$",
        "Tuvalu": "$",
        "Aruba": "ƒ",
        "Azerbaijan": "ман",
        "Bosnia and Herzegovina": "КМ", 
        "Barbados": "$",
        "Bangladesh": "৳",
        "Bulgaria": "лв",
        "Bahrain": "ب.د",
        "Burundi": "₣",
        "Bermuda": "$",
        "Brunei": "$",
        "Singapore": "$",
        "Bolivia": "Bs.",
        "Brazil": "R$",
        "Bahamas": "$",
        "Bhutan": "Nu.",
        "Botswana": "P",
        "Belarus": "Br",
        "Belize": "$",
        "Canada": "$",
        "Congo (Kinshasa)": "₣",
        "Liechtenstein": "₣",
        "Switzerland": "₣",
        "Chile": "$",
        "China": "¥",
        "Colombia": "$",
        "Costa Rica": "₡",
        "Cuba": "$",
        "Cape Verde": "$",
        "Czech Republic": "Kč",
        "Djibouti": "₣",
        "Denmark": "kr",
        "Dominican Republic": "$",
        "Algeria": "د.ج",
        "Egypt": "£",
        "Eritrea": "Nfk",
        "Ethiopia": "ብር",
        "Akrotiri and Dhekelia": "€",
        "Andorra": "€",
        "Austria": "€",
        "Belgium": "€",
        "Cyprus": "€",
        "Estonia": "€",
        "Finland": "€",
        "France": "€",
        "Germany": "€",
        "Greece": "€",
        "Ireland": "€",
        "Italy": "€",
        "Kosovo": "€",
        "Latvia": "€",
        "Lithuania": "€",
        "Luxembourg": "€",
        "Malta": "€",
        "Monaco": "€",
        "Montenegro": "€",
        "Netherlands": "€",
        "Portugal": "€",
        "San-Marino": "€",
        "Slovakia": "€",
        "Slovenia": "€",
        "Spain": "€",
        "Vatican": "€",
        "Fiji": "$",
        "Falkland Islands": "£",
        "Alderney": "£",
        "British Indian Ocean Territory": "£",
        "Great Britain": "£",
        "Isle of Maine": "£",
        "Georgia": "ლ",
        "South Ossetia": "ლ",
        "Ghana": "₵",
        "Gibraltar": "£",
        "Gambia": "D",
        "Guinea": "₣",
        "Guatemala": "Q",
        "Guyana": "$",
        "Hong Kong": "$",
        "Honduras": "L",
        "Croatia": "Kn",
        "Haiti": "G",
        "Hungary": "Ft",
        "Indonesia": "Rp",
        "Israel": "₪",
        "Palestine": "₪",
        "India": "₹",
        "Iraq": "ع.د",
        "Iran": "﷼",
        "Iceland": "Kr",
        "Jamaica": "$",
        "Jordan": "د.ا",
        "Japan": "¥",
        "Kenya": "Sh",
        "Kyrgyzstan": "Лв",
        "Cambodia": "៛",
        "North Korea": "₩",
        "South Korea": "₩",
        "Kuwait": "د.ك",
        "Cayman Islands": "$",
        "Kazakhstan": "〒",
        "Laos": "₭",
        "Lebanon": "ل.ل",
        "Sri Lanka": "Rs",
        "Liberia": "$",
        "Lesotho": "L",
        "Libya": "ل.د",
        "Morocco": "د.م.",
        "Moldova": "L",
        "Madagascar": "Ar",
        "Macedonia": "ден",
        "Myanmar (Burma)": "K",
        "Mongolia": "₮",
        "Macao": "P",
        "Mauritania": "UM",
        "Mauritius": "₨",
        "Maldives": "ރ.",
        "Malawi": "MK",
        "Mexico": "$",
        "Malaysia": "RM",
        "Mozambique": "MTn",
        "Namibia": "$",
        "Nigeria": "₦",
        "Nicaragua": "C$",
        "Norway": "kr",
        "Nepal": "₨",
        "Cook Islands": "$",
        "New Zealand": "$",
        "Niue": "$",
        "Pitcairn Island": "$",
        "Oman": "ر.ع.",
        "Panama": "B/.",
        "Peru": "S/.",
        "Papua New Guinea": "K",
        "Philippines": "₱",
        "Pakistan": "₨",
        "Poland": "zł",
        "Paraguay": "₲",
        "Qatar": "ر.ق",
        "Romania": "L",
        "Serbia": "din",
        "Russia": "р.",
        "Rwanda": "₣",
        "Saudi Arabia": "ر.س",
        "Solomon Islands": "$",
        "Seychelles": "₨",
        "Sudan": "£",
        "Sweden": "kr",
        "Ascension Island": "£",
        "Saint Helena": "£",
        "Tristan da Cunha": "£",
        "Sierra Leone": "Le",
        "Somalia": "Sh",
        "Suriname": "$",
        "Sao Tome and Principe": "Db",
        "Syria": "ل.س",
        "Swaziland": "L",
        "Thailand": "฿",
        "Tajikistan": "ЅМ",
        "Turkmenistan": "m",
        "Tunisia": "د.ت",
        "Tonga": "T$",
        "North Cyprus": "₤",
        "Turkey": "₤",
        "Trinidad and Tobago": "$",
        "Taiwan": "$",
        "Tanzania": "Sh",
        "Ukraine": "₴",
        "Uganda": "Sh",
        "American Samoa": "$",
        "British Virgin Islands": "$",
        "Guam": "$",
        "Marshall Islands": "$",
        "Micronesia": "$",
        "Northern Mariana Islands": "$",
        "Pacific Remote islands": "$",
        "Palau": "$",
        "Puerto Rico": "$",
        "Turks and Caicos Islands": "$",
        "United States of America": "$",
        "US Virgin Islands": "$",
        "Uruguay": "$",
        "Uzbekistan": "Лв",
        "Venezuela": "Bs F",
        "Vietnam": "₫",
        "Vanuatu": "Vt",
        "Samoa": "T",
        "Benin": "₣",
        "Burkina Faso": "₣",
        "Cameroon": "₣",
        "Central African Republic": "₣",
        "Chad": "₣",
        "Congo (Brazzaville)": "₣",
        "Côte d'Ivoire": "₣",
        "Equatorial Guinea": "₣",
        "Gabon": "₣",
        "Guinea-Bissau": "₣",
        "Mali": "₣",
        "Niger": "₣",
        "Senegal": "₣",
        "Togo": "₣",
        "Anguilla": "$",
        "Antigua and Barbuda": "$",
        "Dominica": "$",
        "Grenada": "$",
        "Montserrat": "₣",
        "Saint Kitts and Nevis": "$",
        "Saint Lucia": "$",
        "Saint Vincent and Grenadine": "$",
        "French Polynesia": "₣",
        "New Caledonia": "₣",
        "Wallis and Futuna": "₣",
        "Yemen": "﷼",
        "South Africa": "R",
        "Zambia": "ZK",
        "Zimbabwe": "$"
    }
}
